const fontes = [
  { codigo: 'FEFC', descricao: 'FUNDO ESPECIAL DE FINANCIAMENTO DE CAMPANHA' },
  { codigo: 'FP', descricao: 'FUNDO PARTIDARIO' },
  { codigo: 'OR', descricao: 'OUTROS RECURSOS' },
  { codigo: 'RC', descricao: 'RECURSO DE CAMPANHA' },
]

const naturezas = [
  { codigo: 0, descricao: 'FINANCEIRO' },
  { codigo: 1, descricao: 'ESTIMAVEL' },
]

const origens = [
  { codigo: 'CE', descricao: 'COTAS DO FUNDO ESPECIAL DE FINANCIAMENTO DE CAMPANHA' },
  { codigo: 'CF', descricao: 'COTAS FUNDO PARTIDARIO' },
  { codigo: 'PF', descricao: 'RECURSOS DE PESSOAS FISICAS' },
  { codigo: 'PJ', descricao: 'RECURSOS DE PESSOAS JURIDICAS' },
  { codigo: 'CA', descricao: 'RECURSOS DE CANDIDATOS' },
  { codigo: 'PP', descricao: 'RECURSOS DE PARTIDO POLITICO' },
  { codigo: 'NI', descricao: 'ORIGEM NÃO IDENTIFICADA' },
]

const candidaturas = [
  { codigo: 'PRE', descricao: 'PRESIDENTE' },
  { codigo: 'VPS', descricao: 'VICE-PRESIDENTE' },
  { codigo: 'GOV', descricao: 'GOVERNADOR' },
  { codigo: 'VGO', descricao: 'VICE-GOVERNADOR' },
  { codigo: 'SEN', descricao: 'SENADOR' },
  { codigo: '1SE', descricao: '1º SUPLENTE' },
  { codigo: '2SE', descricao: '2º SUPLENTE' },
  { codigo: 'PRF', descricao: 'PREFEITO' },
  { codigo: 'VPF', descricao: 'VICE-PREFEITO' },
  { codigo: 'DEF', descricao: 'DEPUTADO FEDERAL' },
  { codigo: 'DES', descricao: 'DEPUTADO ESTADUAL' },
  { codigo: 'DDI', descricao: 'DEPUTADO DISTRITAL' },
  { codigo: 'VER', descricao: 'VEREADOR' },
]

const especies = [
  { codigo: 'AC', descricao: 'AVISO CREDITO' },
  { codigo: 'CC', descricao: 'CARTÃO CREDITO' },
  // { codigo: 'CH', descricao: 'DEPOSITO CHEQUE' },
  { codigo: 'EP', descricao: 'DEPOSITO ESPECIE' },
  { codigo: 'OB', descricao: 'ORDEM BANCARIA' },
  // { codigo: 'OT', descricao: 'OUTROS TÍTULOS CREDITO' },
  { codigo: 'PIX', descricao: 'TRANSFERÊNCIA POR PIX - Tipo: Pix' },
  { codigo: 'TEL', descricao: 'TRANSFERÊNCIA ELETRÔNICA - Tipo: Transferência Eletrônica' },
  { codigo: 'TEB', descricao: 'TRANSFERÊNCIA ELETRÔNICA - Tipo: Boleto' },
  { codigo: 'TED', descricao: 'TRANSFERÊNCIA ELETRÔNICA - Tipo: TED/DOC' },
]

const classificacoesReceita = [
  { codigo: 300, descricao: 'RECURSOS DE ORIGEM NÃO IDENTIFICADA' },
  { codigo: 301, descricao: 'REEMBOLSO DE ADIANTAMENTOS A FORNECEDORE' },
  { codigo: 302, descricao: 'PESSOAL - REEEMBOLSO DE ADIANTAMENTOS A EMPREGADOS - Adiantamentos de 13º salário' },
  { codigo: 303, descricao: 'PESSOAL - REEEMBOLSO DE ADIANTAMENTOS A EMPREGADOS - Adiantamentos de férias' },
  { codigo: 304, descricao: 'PESSOAL - REEEMBOLSO DE ADIANTAMENTOS A EMPREGADOS - Adiantamentos de salários' },
  { codigo: 305, descricao: 'PESSOAL - REEEMBOLSO DE ADIANTAMENTOS A EMPREGADOS - Outros adiantamentos a empregados' },
  { codigo: 306, descricao: 'TRANSPORTES E VIAGENS - REEEMBOLSO DE ADIANTAMENTOS DIVERSOS - ADIANTAMENTOS PARA VIAGENS' },
  { codigo: 307, descricao: 'REEMBOLSO DE OUTROS ADIANTAMENTOS DIVERSOS' },
  { codigo: 308, descricao: 'RECUPERAÇÃO DE DEPÓSITOS RESTITUÍVEIS E VALORES VINCULADOS - DEPÓSITOS EXTRAJUDICIAIS' },
  { codigo: 309, descricao: 'RECUPERAÇÃO DE DEPÓSITOS RESTITUÍVEIS E VALORES VINCULADOS - DEPÓSITOS JUDICIAIS' },
  { codigo: 310, descricao: 'OBTENÇÃO DE RECURSOS POR MEIO DE EMPRÉSTIMOS BANCÁRIOS A PAGAR' },
  { codigo: 311, descricao: 'OBTENÇÃO DE RECURSOS POR MEIO DE FINANCIAMENTOS A PAGAR' },
  { codigo: 312, descricao: 'OBTENÇÃO DE RECURSOS POR MEIO DE OUTRAS OBRIGAÇÕES A PAGAR' },
  { codigo: 313, descricao: 'FUNDO PARTIDÁRIO - DIREÇÃO NACIONAL - Cotas recebidas em recursos financeiros - Tribunal Superior Eleitoral' },
  { codigo: 314, descricao: 'DOAÇÕES PARA MANUTENÇÃO DO PARTIDO - PESSOAS FÍSICAS - Em recursos financeiros' },
  { codigo: 315, descricao: 'DOAÇÕES PARA MANUTENÇÃO DO PARTIDO - PESSOAS FÍSICAS - Em recursos estimáveis em dinheiro' },
  { codigo: 318, descricao: 'CONTRIBUIÇÕES - De parlamentares' },
  { codigo: 319, descricao: 'CONTRIBUIÇÕES - De filiados' },
  { codigo: 320, descricao: 'CONTRIBUIÇÕES - Outras contribuições' },
  { codigo: 321, descricao: 'DOAÇÕES PARA CAMPANHAS ELEITORAIS - Pessoas físicas' },
  { codigo: 323, descricao: 'DOAÇÕES/TRANSFERÊNCIAS PARA CAMPANHAS ELEITORAIS - Recebidas da Direção Nacional' },
  { codigo: 324, descricao: 'DOAÇÕES/TRANSFERÊNCIAS PARA CAMPANHAS ELEITORAIS - Recebidas de direções estaduais' },
  { codigo: 325, descricao: 'DOAÇÕES/TRANSFERÊNCIAS PARA CAMPANHAS ELEITORAIS - Recebidas de direções municipais' },
  { codigo: 326, descricao: 'DOAÇÕES/TRANSFERÊNCIAS PARA CAMPANHAS ELEITORAIS - Recebidas de candidatos' },
  { codigo: 327, descricao: 'DOAÇÕES/TRANSFERÊNCIAS PARA CAMPANHAS ELEITORAIS - Recebidas de outros partidos políticos' },
  { codigo: 328, descricao: 'SOBRAS FINANCEIRAS DE CAMPANHA - candidatos' },
  { codigo: 329, descricao: 'SOBRAS FINANCEIRAS DE CAMPANHA - comitês financeiros' },
  { codigo: 330, descricao: 'SOBRAS FINANCEIRAS DE CAMPANHA - partidos políticos' },
  { codigo: 331, descricao: 'SOBRAS DE CAMPANHA - BENS PERMANENTES ESTIMÁVEIS EM DINHEIRO - Sobras de campanha estimáveis em dinheiro - candidatos' },
  { codigo: 332, descricao: 'SOBRAS DE CAMPANHA - BENS PERMANENTES ESTIMÁVEIS EM DINHEIRO - Sobras de campanha estimáveis em dinheiro partidos políticos' },
  { codigo: 333, descricao: 'TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MANUTENÇÃO DO PARTIDO - Recebidas da Direção Nacional' },
  { codigo: 334, descricao: 'TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MANUTENÇÃO DO PARTIDO - Recebidas de direções estaduais335 TRANSFERÊNCIAS DE RECURSOS FINANCEIROS PARA MANUTENÇÃO DO PARTIDO - Recebidas de direções municipais336 JUROS E OUTRAS RENDAS - Rendimentos de aplicações financeiras' },
  { codigo: 337, descricao: 'JUROS E OUTRAS RENDAS - Descontos obtidos' },
  { codigo: 338, descricao: 'JUROS E OUTRAS RENDAS - Outras receitas financeiras' },
  { codigo: 339, descricao: 'OUTRAS RECEITAS DIVERSAS - Receitas com eventos realizados' },
  { codigo: 340, descricao: 'OUTRAS RECEITAS DIVERSAS - Taxas de inscrição' },
  { codigo: 341, descricao: 'OUTRAS RECEITAS DIVERSAS - Outras receitas diversas' },
  { codigo: 342, descricao: 'SOBRAS FINANCEIRAS NÃO UTILIZADAS PELA FUNDAÇÃO PARTIDÁRIA' },
  { codigo: 343, descricao: 'TRANSFERENCIAS INTRAPARTIDÁRIAS DE ATIVO IMOBILIZADO OU MATERIAIS PARA DIVULGAÇÃO/COMERCIALIZAÇÃO - Recebidas daDireção Nacional' },
  { codigo: 344, descricao: 'TRANSFERENCIAS INTRAPARTIDÁRIAS DE ATIVO IMOBILIZADO OU MATERIAIS PARA DIVULGAÇÃO/COMERCIALIZAÇÃO - Recebidas dedireções estaduais' },
  { codigo: 345, descricao: 'TRANSFERENCIAS INTRAPARTIDÁRIAS DE ATIVO IMOBILIZADO OU MATERIAIS PARA DIVULGAÇÃO/COMERCIALIZAÇÃO - Recebidas dedireções municipais' },
  { codigo: 346, descricao: 'TRANSFERENCIAS INTRAPARTIDÁRIAS DE RECURSOS ESTIMÁVEIS EM DINHEIRO - OBRIGAÇÕES ASSUMIDAS - Doações recebidas daDireção Nacional' },
  { codigo: 347, descricao: 'TRANSFERENCIAS INTRAPARTIDÁRIAS DE RECURSOS ESTIMÁVEIS EM DINHEIRO - OBRIGAÇÕES ASSUMIDAS - Doações recebidas dedireções estaduais' },
  { codigo: 348, descricao: 'TRANSFERENCIAS INTRAPARTIDÁRIAS DE RECURSOS ESTIMÁVEIS EM DINHEIRO - OBRIGAÇÕES ASSUMIDAS - Doações recebidas dedireções municipais' },
  { codigo: 349, descricao: 'GANHOS COM ATIVOS - Valor de venda na alienação de bens do ativo permanente' },
  { codigo: 350, descricao: 'GANHOS COM ATIVOS - Aluguéis' },
  { codigo: 351, descricao: 'GANHOS COM ATIVOS - Venda de materiais de divulgação' },
  { codigo: 352, descricao: 'GANHOS COM ATIVOS - Venda de publicações' },
  { codigo: 353, descricao: 'GANHOS COM ATIVOS - Outros ganhos' },
  { codigo: 395, descricao: 'RECURSOS RECEBIDOS DE FONTES VEDADAS' },
  { codigo: 396, descricao: 'FUNDO ESPECIAL DE FINANCIAMENTO DE CAMPANHA - DIREÇÃO NACIONAL - Cotas recebidas em recursos financeiros - TribunalSuperior Eleitoral' },
  { codigo: 397, descricao: 'DOAÇÕES PARA MANUTENÇÃO DO PARTIDO - FINANCIAMENTO COLETIVO - Em recursos financeiros' },
  { codigo: 398, descricao: 'DOAÇÕES PARA CAMPANHAS ELEITORAIS - FINANCIAMENTO COLETIVO' },
]

const gastos = [
  { codigo: 2, descricao: 'ADIANTAMENTOS DIVERSOS - ADIANTAMENTOS A FORNECEDORES' },
  { codigo: 3, descricao: 'ADIANTAMENTOS DIVERSOS - OUTROS ADIANTAMENTOS DIVERSOS' },
  { codigo: 4, descricao: 'ÁGUA E ESGOTO - DESPESAS ELEITORAIS' },
  { codigo: 5, descricao: 'ÁGUA E ESGOTO - MULHERES' },
  { codigo: 6, descricao: 'ÁGUA E ESGOTO - ORDINÁRIAS' },
  { codigo: 7, descricao: 'ALISTAMENTO - MULHERES' },
  { codigo: 8, descricao: 'ALISTAMENTO - ORDINÁRIAS' },
  { codigo: 9, descricao: 'ALUGUÉIS E CONDOMÍNIOS - LOCAÇÃO DE BENS IMÓVEIS - DESPESAS ELEITORAIS' },
  { codigo: 10, descricao: 'ALUGUÉIS E CONDOMÍNIOS - LOCAÇÃO DE BENS IMÓVEIS - MULHERES' },
  { codigo: 11, descricao: 'ALUGUÉIS E CONDOMÍNIOS - LOCAÇÃO DE BENS IMÓVEIS - ORDINÁRIAS' },
  { codigo: 12, descricao: 'ALUGUÉIS E CONDOMÍNIOS - LOCAÇÃO DE BENS MÓVEIS - DESPESAS ELEITORAIS' },
  { codigo: 13, descricao: 'ALUGUÉIS E CONDOMÍNIOS - LOCAÇÃO DE BENS MÓVEIS - MULHERES' },
  { codigo: 14, descricao: 'ALUGUÉIS E CONDOMÍNIOS - LOCAÇÃO DE BENS MÓVEIS - ORDINÁRIAS' },
  { codigo: 15, descricao: 'ALUGUÉIS E CONDOMÍNIOS - TAXAS DE CONDOMÍNIOS - DESPESAS ELEITORAIS' },
  { codigo: 16, descricao: 'ALUGUÉIS E CONDOMÍNIOS - TAXAS DE CONDOMÍNIOS - MULHERES' },
  { codigo: 17, descricao: 'ALUGUÉIS E CONDOMÍNIOS - TAXAS DE CONDOMÍNIOS - ORDINÁRIAS' },
  { codigo: 18, descricao: 'ASSINATURAS E AQUISIÇÕES DE PERIÓDICOS - DESPESAS ELEITORAIS' },
  { codigo: 19, descricao: 'ASSINATURAS E AQUISIÇÕES DE PERIÓDICOS - MULHERES' },
  { codigo: 20, descricao: 'ASSINATURAS E AQUISIÇÕES DE PERIÓDICOS - ORDINÁRIAS' },
  { codigo: 21, descricao: 'ASSUNÇÃO DE DÍVIDAS DE CAMPANHA - DÍVIDAS DE CANDIDATOS - DESPESAS ELEITORAIS' },
  { codigo: 22, descricao: 'ASSUNÇÃO DE DÍVIDAS DE CAMPANHA - DÍVIDAS DE COMITÊS FINANCEIROS - DESPESAS ELEITORAIS23 ASSUNÇÃO DE DÍVIDAS DE CAMPANHA - DÍVIDAS DE DIRETÓRIOS PARTIDÁRIOS - DESPESAS ELEITORAIS24 ATIVO PERMANENTE - BENS IMÓVEIS - EDIFICAÇÕES' },
  { codigo: 25, descricao: 'ATIVO PERMANENTE - BENS IMÓVEIS - INSTALAÇÕES' },
  { codigo: 26, descricao: 'ATIVO PERMANENTE - BENS IMÓVEIS - OUTROS BENS IMÓVEIS' },
  { codigo: 27, descricao: 'ATIVO PERMANENTE - BENS IMÓVEIS - TERRENOS' },
  { codigo: 28, descricao: 'ATIVO PERMANENTE - BENS INCORPÓREOS - DIREITO DE USO' },
  { codigo: 29, descricao: 'ATIVO PERMANENTE - BENS INCORPÓREOS - MARCAS E PATENTES' },
  { codigo: 30, descricao: 'ATIVO PERMANENTE - BENS INCORPÓREOS - OUTROS BENS INCORPÓREOS' },
  { codigo: 31, descricao: 'ATIVO PERMANENTE - BENS MÓVEIS - ARRENDAMENTO MERCANTIL - EQUIPAMENTOS AUDIOVISUAIS - AM32 ATIVO PERMANENTE - BENS MÓVEIS - ARRENDAMENTO MERCANTIL - EQUIPAMENTOS DE INFORMÁTICA - AM33 ATIVO PERMANENTE - BENS MÓVEIS - ARRENDAMENTO MERCANTIL - EQUIPAMENTOS DE SONORIZAÇÃO - AM34 ATIVO PERMANENTE - BENS MÓVEIS - ARRENDAMENTO MERCANTIL - MÓVEIS E UTENSÍLIOS - AM35 ATIVO PERMANENTE - BENS MÓVEIS - ARRENDAMENTO MERCANTIL - OUTRAS MÁQUINAS E EQUIPAMENTOS - AM36 ATIVO PERMANENTE - BENS MÓVEIS - ARRENDAMENTO MERCANTIL - VEÍCULOS - AM37 ATIVO PERMANENTE - BENS MÓVEIS - EQUIPAMENTOS AUDIOVISUAIS' },
  { codigo: 38, descricao: 'ATIVO PERMANENTE - BENS MÓVEIS - EQUIPAMENTOS DE INFORMÁTICA' },
  { codigo: 39, descricao: 'ATIVO PERMANENTE - BENS MÓVEIS - EQUIPAMENTOS DE SONORIZAÇÃO' },
  { codigo: 40, descricao: 'ATIVO PERMANENTE - BENS MÓVEIS - MÓVEIS E UTENSÍLIOS' },
  { codigo: 41, descricao: 'ATIVO PERMANENTE - BENS MÓVEIS - OUTRAS MÁQUINAS E EQUIPAMENTOS' },
  { codigo: 42, descricao: 'ATIVO PERMANENTE - BENS MÓVEIS - VEÍCULOS' },
  { codigo: 43, descricao: 'ATIVO PERMANENTE - INVESTIMENTOS DIVERSOS - INVESTIMENTOS DIVERSOS' },
  { codigo: 44, descricao: 'ATIVO PERMANENTE - SISTEMAS APLICATIVOS - ARRENDAMENTO MERCANTIL - SISTEMAS DE INFORMÁTICA - AM45 ATIVO PERMANENTE - SISTEMAS APLICATIVOS - SISTEMAS DE INFORMÁTICA' },
  { codigo: 46, descricao: 'COMÍCIOS E MILITÂNCIA DE RUA - DESPESAS ELEITORAIS' },
  { codigo: 47, descricao: 'CONGRESSOS - MULHERES' },
  { codigo: 48, descricao: 'CONGRESSOS - ORDINÁRIAS' },
  { codigo: 49, descricao: 'CONVENÇÕES - MULHERES' },
  { codigo: 50, descricao: 'CONVENÇÕES ELEITORAIS - DESPESAS ELEITORAIS' },
  { codigo: 51, descricao: 'CONVENÇÕES PARTIDÁRIAS - ORDINÁRIAS' },
  { codigo: 52, descricao: 'CÓPIAS, ENCADERNAÇÕES E SERVIÇOS SIMILARES - ORDINÁRIAS' },
  { codigo: 53, descricao: 'CÓPIAS, ENCADERNAÇÕES E SERVIÇOS SIMILARES - DESPESAS ELEITORAIS' },
  { codigo: 54, descricao: 'CÓPIAS, ENCADERNAÇÕES E SERVIÇOS SIMILARES - MULHERES' },
  { codigo: 55, descricao: 'DEPÓSITOS RESTITUÍVEIS E VALORES VINCULADOS - DEPÓSITOS EXTRAJUDICIAIS' },
  { codigo: 56, descricao: 'DEPÓSITOS RESTITUÍVEIS E VALORES VINCULADOS - DEPÓSITOS JUDICIAIS' },
  { codigo: 57, descricao: 'DESPESAS FINANCEIRAS - ATUALIZAÇÃO MONETÁRIA DE EMPRÉSTIMOS' },
  { codigo: 58, descricao: 'DESPESAS FINANCEIRAS - COMISSÕES E TARIFAS BANCÁRIAS' },
  { codigo: 59, descricao: 'DESPESAS FINANCEIRAS - OUTRAS DESPESAS FINANCEIRAS' },
  { codigo: 60, descricao: 'DESPESAS JUDICIAIS - DESPESAS ELEITORAIS' },
  { codigo: 61, descricao: 'DESPESAS JUDICIAIS - MULHERES' },
  { codigo: 62, descricao: 'DESPESAS JUDICIAIS - ORDINÁRIAS' },
  { codigo: 63, descricao: 'ENERGIA ELÉTRICA - DESPESAS ELEITORAIS' },
  { codigo: 64, descricao: 'ENERGIA ELÉTRICA - MULHERES' },
  { codigo: 65, descricao: 'ENERGIA ELÉTRICA - ORDINÁRIAS' },
  { codigo: 66, descricao: 'EVENTOS PROMOCIONAIS - DESPESAS ELEITORAIS' },
  { codigo: 67, descricao: 'EVENTOS PROMOCIONAIS - MULHERES' },
  { codigo: 68, descricao: 'EVENTOS PROMOCIONAIS - ORDINÁRIAS' },
  { codigo: 69, descricao: 'FUNDAÇÃO DE PESQUISA OU DE DOUTRINAÇÃO E EDUCAÇÃO POLÍTICA - FUNDAÇÃO PARTIDÁRIA70 INSTALAÇÃO DE COMITÊS FINANCEIROS E DE CAMPANHA - DESPESAS ELEITORAIS' },
  { codigo: 71, descricao: 'LANCHES E REFEIÇÕES - DESPESAS ELEITORAIS' },
  { codigo: 72, descricao: 'LANCHES E REFEIÇÕES - MULHERES' },
  { codigo: 73, descricao: 'LANCHES E REFEIÇÕES - ORDINÁRIAS' },
  { codigo: 74, descricao: 'MANUTENÇÃO, CONSERVAÇÃO E REPAROS DE BENS - CESSÃO MAO-DE-OBRA - DESPESAS ELEITORAIS75 MANUTENÇÃO, CONSERVAÇÃO E REPAROS DE BENS - CESSÃO MAO-DE-OBRA - MULHERES' },
  { codigo: 76, descricao: 'MANUTENÇÃO, CONSERVAÇÃO E REPAROS DE BENS - CESSÃO MAO-DE-OBRA - ORDINÁRIAS' },
  { codigo: 77, descricao: 'MANUTENÇÃO, CONSERVAÇÃO E REPAROS DE BENS - DESPESAS ELEITORAIS' },
  { codigo: 78, descricao: 'MANUTENÇÃO, CONSERVAÇÃO E REPAROS DE BENS - ENCARGOS SOCIAIS SOBRE CESSÃO MAO-DE-OBRA - DESPESAS ELEITORAIS' },
  { codigo: 79, descricao: 'MANUTENÇÃO, CONSERVAÇÃO E REPAROS DE BENS - ENCARGOS SOCIAIS SOBRE CESSÃO MAO-DE-OBRA - MULHERES' },
  { codigo: 80, descricao: 'MANUTENÇÃO, CONSERVAÇÃO E REPAROS DE BENS - ENCARGOS SOCIAIS SOBRE CESSÃO MAO-DE-OBRA - ORDINÁRIAS' },
  { codigo: 81, descricao: 'MANUTENÇÃO, CONSERVAÇÃO E REPAROS DE BENS - MULHERES' },
  { codigo: 82, descricao: 'MANUTENÇÃO, CONSERVAÇÃO E REPAROS DE BENS - ORDINÁRIAS' },
  { codigo: 83, descricao: 'MATERIAIS PARA COMERCIALIZAÇÃO / DISTRIBUIÇÃO - DESPESAS ELEITORAIS' },
  { codigo: 84, descricao: 'MATERIAIS PARA COMERCIALIZAÇÃO / DISTRIBUIÇÃO - MULHERES' },
  { codigo: 85, descricao: 'MATERIAIS PARA COMERCIALIZAÇÃO / DISTRIBUIÇÃO - ORDINÁRIAS' },
  { codigo: 86, descricao: 'MATERIAL DE CONSUMO - MATERIAIS DE COPA E COZINHA - DESPESAS ELEITORAIS' },
  { codigo: 87, descricao: 'MATERIAL DE CONSUMO - MATERIAIS DE COPA E COZINHA - MULHERES' },
  { codigo: 88, descricao: 'MATERIAL DE CONSUMO - MATERIAIS DE COPA E COZINHA - ORDINÁRIAS' },
  { codigo: 89, descricao: 'MATERIAL DE CONSUMO - MATERIAIS DE EXPEDIENTE - DESPESAS ELEITORAIS' },
  { codigo: 90, descricao: 'MATERIAL DE CONSUMO - MATERIAIS DE EXPEDIENTE - MULHERES' },
  { codigo: 91, descricao: 'MATERIAL DE CONSUMO - MATERIAIS DE EXPEDIENTE - ORDINÁRIAS' },
  { codigo: 92, descricao: 'MATERIAL DE CONSUMO - MATERIAIS DE INFORMÁTICA - DESPESAS ELEITORAIS' },
  { codigo: 93, descricao: 'MATERIAL DE CONSUMO - MATERIAIS DE INFORMÁTICA - MULHERES' },
  { codigo: 94, descricao: 'MATERIAL DE CONSUMO - MATERIAIS DE INFORMÁTICA - ORDINÁRIAS' },
  { codigo: 95, descricao: 'MATERIAL DE CONSUMO - MATERIAIS DE LIMPEZA - DESPESAS ELEITORAIS' },
  { codigo: 96, descricao: 'MATERIAL DE CONSUMO - MATERIAIS DE LIMPEZA - MULHERES' },
  { codigo: 97, descricao: 'MATERIAL DE CONSUMO - MATERIAIS DE LIMPEZA - ORDINÁRIAS' },
  { codigo: 98, descricao: 'MATERIAL DE CONSUMO - MATERIAIS IMPRESSOS - DESPESAS ELEITORAIS' },
  { codigo: 99, descricao: 'MATERIAL DE CONSUMO - MATERIAIS IMPRESSOS - MULHERES' },
  { codigo: 100, descricao: 'MATERIAL DE CONSUMO - MATERIAIS IMPRESSOS - ORDINÁRIAS' },
  { codigo: 101, descricao: 'MATERIAL DE CONSUMO - OUTROS MATERIAIS DE CONSUMO - DESPESAS ELEITORAIS' },
  { codigo: 102, descricao: 'MATERIAL DE CONSUMO - OUTROS MATERIAIS DE CONSUMO - MULHERES' },
  { codigo: 103, descricao: 'MATERIAL DE CONSUMO - OUTROS MATERIAIS DE CONSUMO - ORDINÁRIAS' },
  { codigo: 104, descricao: 'OBRIGAÇÕES DIVERSAS - EMPRÉSTIMOS BANCÁRIOS A PAGAR' },
  { codigo: 105, descricao: 'OBRIGAÇÕES DIVERSAS - FINANCIAMENTOS A PAGAR' },
  { codigo: 106, descricao: 'OBRIGAÇÕES DIVERSAS - OUTRAS OBRIGAÇÕES A PAGAR' },
  { codigo: 107, descricao: 'OUTRAS DESPESAS COM PROPAGANDA DOUTRINÁRIA E POLÍTICA - DESPESAS ELEITORAIS' },
  { codigo: 108, descricao: 'OUTRAS DESPESAS COM PROPAGANDA DOUTRINÁRIA E POLÍTICA - MULHERES' },
  { codigo: 109, descricao: 'OUTRAS DESPESAS COM PROPAGANDA DOUTRINÁRIA E POLÍTICA - ORDINÁRIAS' },
  { codigo: 110, descricao: 'OUTRAS DESPESAS DE CAMPANHA ELEITORAL - DESPESAS ELEITORAIS' },
  { codigo: 111, descricao: 'OUTRAS DESPESAS GERAIS - DESPESAS ELEITORAIS' },
  { codigo: 112, descricao: 'OUTRAS DESPESAS GERAIS - MULHERES' },
  { codigo: 113, descricao: 'OUTRAS DESPESAS GERAIS - ORDINÁRIAS' },
  { codigo: 114, descricao: 'OUTRAS DESPESAS PARA PARTICIPAÇÃO DA MULHER NA POLÍTICA - MULHERES' },
  { codigo: 115, descricao: 'OUTROS DESPESAS ELEITORAIS' },
  { codigo: 116, descricao: 'OUTROS MATERIAIS PARA COMERCIALIZAÇÃO / DISTRIBUIÇÃO - DESPESAS ELEITORAIS' },
  { codigo: 117, descricao: 'OUTROS MATERIAIS PARA COMERCIALIZAÇÃO / DISTRIBUIÇÃO - MULHERES' },
  { codigo: 118, descricao: 'OUTROS MATERIAIS PARA COMERCIALIZAÇÃO / DISTRIBUIÇÃO - ORDINÁRIAS' },
  { codigo: 119, descricao: 'OUTROS MULHERES' },
  { codigo: 120, descricao: 'OUTROS ORDINÁRIAS' },
  { codigo: 121, descricao: 'PERDAS COM ATIVOS - PERDA NA ALIENAÇÃO DE BENS' },
  { codigo: 122, descricao: 'PERDAS COM ATIVOS - SINISTROS, ROUBOS E OUTRAS PERDAS' },
  { codigo: 123, descricao: 'PESQUISAS E TESTES DE OPINIÃO PÚBLICA - DESPESAS ELEITORAIS' },
  { codigo: 124, descricao: 'PESQUISAS E TESTES DE OPINIÃO PÚBLICA - MULHERES' },
  { codigo: 125, descricao: 'PESQUISAS E TESTES DE OPINIÃO PÚBLICA - ORDINÁRIAS' },
  { codigo: 126, descricao: 'PESSOAL - 13º SALÁRIO - DESPESAS ELEITORAIS' },
  { codigo: 127, descricao: 'PESSOAL - 13º SALÁRIO - MULHERES' },
  { codigo: 128, descricao: 'PESSOAL - 13º SALÁRIO - ORDINÁRIAS' },
  { codigo: 129, descricao: 'PESSOAL - ADIANTAMENTOS A EMPREGADOS - Adiantamentos de 13º salário' },
  { codigo: 130, descricao: 'PESSOAL - ADIANTAMENTOS A EMPREGADOS - Adiantamentos de férias' },
  { codigo: 131, descricao: 'PESSOAL - ADIANTAMENTOS A EMPREGADOS - Adiantamentos de salários' },
  { codigo: 132, descricao: 'PESSOAL - ADIANTAMENTOS A EMPREGADOS - Outros adiantamentos a empregados' },
  { codigo: 133, descricao: 'PESSOAL - ALIMENTAÇÃO DO TRABALHADOR - DESPESAS ELEITORAIS' },
  { codigo: 134, descricao: 'PESSOAL - ALIMENTAÇÃO DO TRABALHADOR - MULHERES' },
  { codigo: 135, descricao: 'PESSOAL - ALIMENTAÇÃO DO TRABALHADOR - ORDINÁRIAS' },
  { codigo: 136, descricao: 'PESSOAL - ASSISTÊNCIA MÉDICA E SOCIAL - DESPESAS ELEITORAIS' },
  { codigo: 137, descricao: 'PESSOAL - ASSISTÊNCIA MÉDICA E SOCIAL - MULHERES' },
  { codigo: 138, descricao: 'PESSOAL - ASSISTÊNCIA MÉDICA E SOCIAL - ORDINÁRIAS' },
  { codigo: 139, descricao: 'PESSOAL - AUXÍLIO-TRANSPORTE - DESPESAS ELEITORAIS' },
  { codigo: 140, descricao: 'PESSOAL - AUXÍLIO-TRANSPORTE - MULHERES' },
  { codigo: 141, descricao: 'PESSOAL - AUXÍLIO-TRANSPORTE - ORDINÁRIAS' },
  { codigo: 142, descricao: 'PESSOAL - CONTRIBUIÇÃO SINDICAL - DESPESAS ELEITORAIS' },
  { codigo: 143, descricao: 'PESSOAL - CONTRIBUIÇÃO SINDICAL - MULHERES' },
  { codigo: 144, descricao: 'PESSOAL - CONTRIBUIÇÃO SINDICAL - ORDINÁRIAS' },
  { codigo: 145, descricao: 'PESSOAL - ESTAGIÁRIOS - DESPESAS ELEITORAIS' },
  { codigo: 146, descricao: 'PESSOAL - ESTAGIÁRIOS - MULHERES' },
  { codigo: 147, descricao: 'PESSOAL - ESTAGIÁRIOS - ORDINÁRIAS' },
  { codigo: 148, descricao: 'PESSOAL - FÉRIAS - DESPESAS ELEITORAIS' },
  { codigo: 149, descricao: 'PESSOAL - FÉRIAS - MULHERES' },
  { codigo: 150, descricao: 'PESSOAL - FÉRIAS - ORDINÁRIAS' },
  { codigo: 151, descricao: 'PESSOAL - FGTS - DESPESAS ELEITORAIS' },
  { codigo: 152, descricao: 'PESSOAL - FGTS - MULHERES' },
  { codigo: 153, descricao: 'PESSOAL - FGTS - ORDINÁRIAS' },
  { codigo: 154, descricao: 'PESSOAL - IRRF - DESPESAS ELEITORAIS' },
  { codigo: 155, descricao: 'PESSOAL - IRRF - MULHERES' },
  { codigo: 156, descricao: 'PESSOAL - IRRF - ORDINÁRIAS' },
  { codigo: 157, descricao: 'PESSOAL - OUTRAS DESPESAS COM PESSOAL - DESPESAS ELEITORAIS' },
  { codigo: 158, descricao: 'PESSOAL - OUTRAS DESPESAS COM PESSOAL - MULHERES' },
  { codigo: 159, descricao: 'PESSOAL - OUTRAS DESPESAS COM PESSOAL - ORDINÁRIAS' },
  { codigo: 160, descricao: 'PESSOAL - PIS SOBRE FOLHA DE PAGAMENTO - DESPESAS ELEITORAIS' },
  { codigo: 161, descricao: 'PESSOAL - PIS SOBRE FOLHA DE PAGAMENTO - MULHERES' },
  { codigo: 162, descricao: 'PESSOAL - PIS SOBRE FOLHA DE PAGAMENTO - ORDINÁRIAS' },
  { codigo: 163, descricao: 'PESSOAL - PREVIDÊNCIA SOCIAL - DESPESAS ELEITORAIS' },
  { codigo: 164, descricao: 'PESSOAL - PREVIDÊNCIA SOCIAL - MULHERES' },
  { codigo: 165, descricao: 'PESSOAL - PREVIDÊNCIA SOCIAL - ORDINÁRIAS' },
  { codigo: 166, descricao: 'PESSOAL - RESCISÃO DE CONTRATO DE TRABALHO - DESPESAS ELEITORAIS' },
  { codigo: 167, descricao: 'PESSOAL - RESCISÃO DE CONTRATO DE TRABALHO - MULHERES' },
  { codigo: 168, descricao: 'PESSOAL - RESCISÃO DE CONTRATO DE TRABALHO - ORDINÁRIAS' },
  { codigo: 169, descricao: 'PESSOAL - SALÁRIOS E ORDENADOS - DESPESAS ELEITORAIS' },
  { codigo: 170, descricao: 'PESSOAL - SALÁRIOS E ORDENADOS - MULHERES' },
  { codigo: 171, descricao: 'PESSOAL - SALÁRIOS E ORDENADOS - ORDINÁRIAS' },
  { codigo: 172, descricao: 'PESSOAL - SEGURO DE VIDA DE EMPREGADOS - DESPESAS ELEITORAIS' },
  { codigo: 173, descricao: 'PESSOAL - SEGURO DE VIDA DE EMPREGADOS - MULHERES' },
  { codigo: 174, descricao: 'PESSOAL - SEGURO DE VIDA DE EMPREGADOS - ORDINÁRIAS' },
  { codigo: 175, descricao: 'PRODUÇÃO DE AUDIOVISUAIS - DESPESAS ELEITORAIS' },
  { codigo: 176, descricao: 'PRODUÇÃO DE AUDIOVISUAIS - MULHERES' },
  { codigo: 177, descricao: 'PRODUÇÃO DE AUDIOVISUAIS - ORDINÁRIAS' },
  { codigo: 178, descricao: 'PROPAGANDA E PUBLICIDADE - DESPESAS ELEITORAIS' },
  { codigo: 179, descricao: 'PROPAGANDA E PUBLICIDADE - MULHERES' },
  { codigo: 180, descricao: 'PROPAGANDA E PUBLICIDADE - ORDINÁRIAS' },
  { codigo: 181, descricao: 'PUBLICAÇÕES - DESPESAS ELEITORAIS' },
  { codigo: 182, descricao: 'PUBLICAÇÕES - MULHERES' },
  { codigo: 183, descricao: 'PUBLICAÇÕES - ORDINÁRIAS' },
  { codigo: 184, descricao: 'RÁDIO E TELEVISÃO - DESPESAS ELEITORAIS' },
  { codigo: 185, descricao: 'RÁDIO E TELEVISÃO - MULHERES' },
  { codigo: 186, descricao: 'RÁDIO E TELEVISÃO - ORDINÁRIAS' },
  { codigo: 187, descricao: 'SEGURANÇA E VIGILÂNCIA - CESSÃO MAO-DE-OBRA - DESPESAS ELEITORAIS' },
  { codigo: 188, descricao: 'SEGURANÇA E VIGILÂNCIA - CESSÃO MAO-DE-OBRA - MULHERES' },
  { codigo: 189, descricao: 'SEGURANÇA E VIGILÂNCIA - CESSÃO MAO-DE-OBRA - ORDINÁRIAS' },
  { codigo: 190, descricao: 'SEGURANÇA E VIGILÂNCIA - DESPESAS ELEITORAIS' },
  { codigo: 191, descricao: 'SEGURANÇA E VIGILÂNCIA - ENCARGOS SOCIAIS SOBRE CESSÃO MAO-DE-OBRA - DESPESAS ELEITORAIS192 SEGURANÇA E VIGILÂNCIA - ENCARGOS SOCIAIS SOBRE CESSÃO MAO-DE-OBRA - MULHERES' },
  { codigo: 193, descricao: 'SEGURANÇA E VIGILÂNCIA - ENCARGOS SOCIAIS SOBRE CESSÃO MAO-DE-OBRA - ORDINÁRIAS' },
  { codigo: 194, descricao: 'SEGURANÇA E VIGILÂNCIA - MULHERES' },
  { codigo: 195, descricao: 'SEGURANÇA E VIGILÂNCIA - ORDINÁRIAS' },
  { codigo: 196, descricao: 'SEGUROS - DESPESAS ELEITORAIS' },
  { codigo: 197, descricao: 'SEGUROS - MULHERES' },
  { codigo: 198, descricao: 'SEGUROS - ORDINÁRIAS' },
  { codigo: 199, descricao: 'SEMINÁRIOS - MULHERES' },
  { codigo: 200, descricao: 'SEMINÁRIOS - ORDINÁRIAS' },
  { codigo: 201, descricao: 'SERVIÇOS CARTORÁRIOS - DESPESAS ELEITORAIS' },
  { codigo: 202, descricao: 'SERVIÇOS CARTORÁRIOS - MULHERES' },
  { codigo: 203, descricao: 'SERVIÇOS CARTORÁRIOS - ORDINÁRIAS' },
  { codigo: 204, descricao: 'SERVIÇOS DE LIMPEZA - CESSÃO MAO-DE-OBRA - DESPESAS ELEITORAIS' },
  { codigo: 205, descricao: 'SERVIÇOS DE LIMPEZA - CESSÃO MAO-DE-OBRA - MULHERES' },
  { codigo: 206, descricao: 'SERVIÇOS DE LIMPEZA - CESSÃO MAO-DE-OBRA - ORDINÁRIAS' },
  { codigo: 207, descricao: 'SERVIÇOS DE LIMPEZA - DESPESAS ELEITORAIS' },
  { codigo: 208, descricao: 'SERVIÇOS DE LIMPEZA - ENCARGOS SOCIAIS SOBRE CESSÃO MAO-DE-OBRA - DESPESAS ELEITORAIS209 SERVIÇOS DE LIMPEZA - ENCARGOS SOCIAIS SOBRE CESSÃO MAO-DE-OBRA - MULHERES' },
  { codigo: 210, descricao: 'SERVIÇOS DE LIMPEZA - ENCARGOS SOCIAIS SOBRE CESSÃO MAO-DE-OBRA - ORDINÁRIAS' },
  { codigo: 211, descricao: 'SERVIÇOS DE LIMPEZA - MULHERES' },
  { codigo: 212, descricao: 'SERVIÇOS DE LIMPEZA - ORDINÁRIAS' },
  { codigo: 213, descricao: 'SERVIÇOS POSTAIS - DESPESAS ELEITORAIS' },
  { codigo: 214, descricao: 'SERVIÇOS POSTAIS - MULHERES' },
  { codigo: 215, descricao: 'SERVIÇOS POSTAIS - ORDINÁRIAS' },
  { codigo: 216, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - ENCARGOS SOCIAIS - DESPESAS ELEITORAIS' },
  { codigo: 217, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - ENCARGOS SOCIAIS - MULHERES' },
  { codigo: 218, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - ENCARGOS SOCIAIS - ORDINÁRIAS' },
  { codigo: 219, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - OUTROS SERVIÇOS TÉCNICOS E PROFISSIONAIS - DESPESAS ELEITORAIS220 SERVIÇOS TÉCNICO-PROFISSIONAIS - OUTROS SERVIÇOS TÉCNICOS E PROFISSIONAIS - MULHERES' },
  { codigo: 221, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - OUTROS SERVIÇOS TÉCNICOS E PROFISSIONAIS - ORDINÁRIAS' },
  { codigo: 222, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - SERVIÇOS CONTÁBEIS - DESPESAS ELEITORAIS' },
  { codigo: 223, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - SERVIÇOS CONTÁBEIS - MULHERES' },
  { codigo: 224, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - SERVIÇOS CONTÁBEIS - ORDINÁRIAS' },
  { codigo: 225, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - SERVIÇOS DE CONSULTORIA JURÍDICA - DESPESAS ELEITORAIS226 SERVIÇOS TÉCNICO-PROFISSIONAIS - SERVIÇOS DE CONSULTORIA JURÍDICA - MULHERES' },
  { codigo: 227, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - SERVIÇOS DE CONSULTORIA JURÍDICA - ORDINÁRIAS' },
  { codigo: 228, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - SERVIÇOS DE INFORMÁTICA - DESPESAS ELEITORAIS' },
  { codigo: 229, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - SERVIÇOS DE INFORMÁTICA - MULHERES' },
  { codigo: 230, descricao: 'SERVIÇOS TÉCNICO-PROFISSIONAIS - SERVIÇOS DE INFORMÁTICA - ORDINÁRIAS' },
  { codigo: 231, descricao: 'TELECOMUNICAÇÕES E INTERNET - DESPESAS ELEITORAIS' },
  { codigo: 232, descricao: 'TELECOMUNICAÇÕES E INTERNET - MULHERES' },
  { codigo: 233, descricao: 'TELECOMUNICAÇÕES E INTERNET - ORDINÁRIAS' },
  { codigo: 234, descricao: 'TRANSFERÊNCIAS EFETUADAS - ASSUNÇÃO DE OBRIGAÇÕES - RECURSOS ESTIMÁVEIS EM DINHEIRO CANDIDATO236 ASSUNÇÃO DE OBRIGAÇÕES - DESPESAS ORDINÁRIAS REALIZADAS POR DIREÇÃO ESTADUAL' },
  { codigo: 237, descricao: 'ASSUNÇÃO DE OBRIGAÇÕES - DESPESAS ORDINÁRIAS REALIZADAS POR DIREÇÃO MUNICIPAL' },
  { codigo: 238, descricao: 'ASSUNÇÃO DE OBRIGAÇÕES - DESPESAS ORDINÁRIAS REALIZADAS POR DIREÇÃO NACIONAL' },
  { codigo: 249, descricao: 'TRANSPORTES E VIAGENS - ADIANTAMENTOS DIVERSOS - ADIANTAMENTOS PARA VIAGENS' },
  { codigo: 250, descricao: 'TRANSPORTES E VIAGENS - COMBUSTÍVEIS, ÓLEOS E LUBRIFICANTES - DESPESAS ELEITORAIS' },
  { codigo: 251, descricao: 'TRANSPORTES E VIAGENS - COMBUSTÍVEIS, ÓLEOS E LUBRIFICANTES - MULHERES' },
  { codigo: 252, descricao: 'TRANSPORTES E VIAGENS - COMBUSTÍVEIS, ÓLEOS E LUBRIFICANTES - ORDINÁRIAS' },
  { codigo: 253, descricao: 'TRANSPORTES E VIAGENS - FRETAMENTO DE AERONAVES - DESPESAS ELEITORAIS' },
  { codigo: 254, descricao: 'TRANSPORTES E VIAGENS - FRETAMENTO DE AERONAVES - MULHERES' },
  { codigo: 255, descricao: 'TRANSPORTES E VIAGENS - FRETAMENTO DE AERONAVES - ORDINÁRIAS' },
  { codigo: 256, descricao: 'TRANSPORTES E VIAGENS - FRETES E CARRETOS - DESPESAS ELEITORAIS' },
  { codigo: 257, descricao: 'TRANSPORTES E VIAGENS - FRETES E CARRETOS - MULHERES' },
  { codigo: 258, descricao: 'TRANSPORTES E VIAGENS - FRETES E CARRETOS - ORDINÁRIAS' },
  { codigo: 259, descricao: 'TRANSPORTES E VIAGENS - HOSPEDAGENS E ESTADIAS - DESPESAS ELEITORAIS' },
  { codigo: 260, descricao: 'TRANSPORTES E VIAGENS - HOSPEDAGENS E ESTADIAS - MULHERES' },
  { codigo: 261, descricao: 'TRANSPORTES E VIAGENS - HOSPEDAGENS E ESTADIAS - ORDINÁRIAS' },
  { codigo: 262, descricao: 'TRANSPORTES E VIAGENS - OUTRAS DESPESAS COM TRANSPORTES E VIAGENS - DESPESAS ELEITORAIS263 TRANSPORTES E VIAGENS - OUTRAS DESPESAS COM TRANSPORTES E VIAGENS - MULHERES' },
  { codigo: 264, descricao: 'TRANSPORTES E VIAGENS - OUTRAS DESPESAS COM TRANSPORTES E VIAGENS - ORDINÁRIAS' },
  { codigo: 265, descricao: 'TRANSPORTES E VIAGENS - PASSAGENS AÉREAS - DESPESAS ELEITORAIS' },
  { codigo: 266, descricao: 'TRANSPORTES E VIAGENS - PASSAGENS AÉREAS - MULHERES' },
  { codigo: 267, descricao: 'TRANSPORTES E VIAGENS - PASSAGENS AÉREAS - ORDINÁRIAS' },
  { codigo: 268, descricao: 'TRANSPORTES E VIAGENS - PEDÁGIOS - DESPESAS ELEITORAIS' },
  { codigo: 269, descricao: 'TRANSPORTES E VIAGENS - PEDÁGIOS - MULHERES' },
  { codigo: 270, descricao: 'TRANSPORTES E VIAGENS - PEDÁGIOS - ORDINÁRIAS' },
  { codigo: 271, descricao: 'TRANSPORTES E VIAGENS - SERVIÇOS DE TÁXI - DESPESAS ELEITORAIS' },
  { codigo: 272, descricao: 'TRANSPORTES E VIAGENS - SERVIÇOS DE TÁXI - MULHERES' },
  { codigo: 273, descricao: 'TRANSPORTES E VIAGENS - SERVIÇOS DE TÁXI - ORDINÁRIAS' },
  { codigo: 274, descricao: 'TRANSPORTES E VIAGENS - TRANSPORTE RODOVIÁRIO - DESPESAS ELEITORAIS' },
  { codigo: 275, descricao: 'TRANSPORTES E VIAGENS - TRANSPORTE RODOVIÁRIO - MULHERES' },
  { codigo: 276, descricao: 'TRANSPORTES E VIAGENS - TRANSPORTE RODOVIÁRIO - ORDINÁRIAS' },
  { codigo: 277, descricao: 'TRIBUTOS - IPTU - DESPESAS ELEITORAIS' },
  { codigo: 278, descricao: 'TRIBUTOS - IPTU - ORDINÁRIAS' },
  { codigo: 279, descricao: 'TRIBUTOS - IPVA - DESPESAS ELEITORAIS' },
  { codigo: 280, descricao: 'TRIBUTOS - IPVA - ORDINÁRIAS' },
  { codigo: 281, descricao: 'TRIBUTOS - OUTROS TRIBUTOS - DESPESAS ELEITORAIS' },
  { codigo: 282, descricao: 'TRIBUTOS - OUTROS TRIBUTOS - ORDINÁRIAS' },
  { codigo: 283, descricao: 'TRIBUTOS - TAXAS - DESPESAS ELEITORAIS' },
  { codigo: 284, descricao: 'TRIBUTOS - TAXAS - ORDINÁRIAS' },
  { codigo: 399, descricao: 'DESPESAS COM ALISTAMENTO - ELEITORAIS' },
  { codigo: 400, descricao: 'DESPESAS COM CONVENÇÕES PARTIDÁRIAS - ELEITORAIS' },
  { codigo: 401, descricao: 'DESPESAS COM CRIAÇÃO E INCLUSÃO DE PÁGINAS NA INTERNET OU REDES SOCIAIS - ELEITORAIS' },
  { codigo: 402, descricao: 'DESPESAS COM EVENTOS DE PROMOÇÃO DE CANDIDATURAS - ELEITORAIS' },
  { codigo: 403, descricao: 'DESPESAS COM IMPULSIONAMENTO DE CONTEÚDOS DE INTERNET OU REDES SOCIAIS - ELEITORAIS404 DESPESAS COM PRODUÇÃO DE JINGLES, VINHETAS E SLOGANS - ELEITORAIS' },
  { codigo: 405, descricao: 'DESPESAS COM PUBLICIDADE POR ADESIVOS - ELEITORAIS' },
  { codigo: 406, descricao: 'DESPESAS COM PUBLICIDADE POR CARROS DE SOM - ELEITORAIS' },
  { codigo: 407, descricao: 'DESPESAS COM PUBLICIDADE POR MATERIAIS IMPRESSOS - ELEITORAIS' },
  { codigo: 408, descricao: 'DESPESAS COM REEMBOLSO DE GASTOS REALIZADOS POR ELEITORES - ELEITORAIS' },
  { codigo: 409, descricao: 'DESPESAS FINANCEIRAS - JUROS E MULTAS' },
  { codigo: 410, descricao: 'DESPESAS FINANCEIRAS - TAXAS DE ADMINISTRAÇÃO DE CARTÕES DE CRÉDITO OU DÉBITO411 DESPESAS FINANCEIRAS - TAXAS DE ADMINISTRAÇÃO DE FINANCIAMENTO COLETIVO412 DESPESAS GERAIS - MENSALIDADES, ANUIDADES E CONGÊNERES DEVIDOS A ORGANISMOS PARTIDÁRIOS INTERNACIONAIS -DESPESAS ELEITORAIS' },
  { codigo: 413, descricao: 'DESPESAS GERAIS - MENSALIDADES, ANUIDADES E CONGÊNERES DEVIDOS A ORGANISMOS PARTIDÁRIOS INTERNACIONAIS - MULHERES' },
  { codigo: 414, descricao: 'DESPESAS GERAIS - MENSALIDADES, ANUIDADES E CONGÊNERES DEVIDOS A ORGANISMOS PARTIDÁRIOS INTERNACIONAIS - ORDINÁRIAS' },
  { codigo: 415, descricao: 'RECOLHIMENTOS AO ERÁRIO - DESPESAS COM MULTAS ELEITORAIS' },
  { codigo: 416, descricao: 'RECOLHIMENTOS AO ERÁRIO - RESSARCIMENTO - IRREGULARIDADES NA APLICAÇÃO DE RECURSOS PÚBLICOS (FEFC E FUNDOPARTIDÁRIO)' },
  { codigo: 417, descricao: 'RECOLHIMENTOS AO ERÁRIO - RESSARCIMENTO - RECEBIMENTO DE RECURSOS DE FONTES VEDADAS' },
  { codigo: 418, descricao: 'RECOLHIMENTOS AO ERÁRIO - RESSARCIMENTO - RECEBIMENTO DE RECURSOS DE ORIGEM NÃO IDENTIFICADA' },
  { codigo: 419, descricao: 'RECOLHIMENTOS AO ERÁRIO - RESSARCIMENTO - SOBRAS DO FUNDO ESPECIAL DE FINANCIAMENTO DE CAMPANHA' },
]

const documentos = ['BOLETO', 'CONTRATO', 'FISCAL', 'FATURA', 'RECIBO', 'OUTRO']

export { fontes, naturezas, origens, candidaturas, especies, classificacoesReceita, gastos, documentos }

