import Menu from '@/components/Menu'
import './globals.css'
// eslint-disable-next-line camelcase
import { Roboto_Flex, Montserrat } from 'next/font/google'
import { cookies } from 'next/headers'
import React from 'react'

const roboto = Roboto_Flex({ subsets: ['latin'], variable: '--font-roboto' })
const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const isAuthenticated = cookies().has('token')

  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable} font-sans`}>
        {isAuthenticated ? (
          <div className="grid h-screen min-h-screen w-screen grid-cols-[250px_auto]">
            <Menu />
            <main className="overflow-x-auto p-6">{children}</main>
          </div>
        ) : (
          children
        )}
      </body>
    </html>
  )
}
