import Menu from "@/components/Menu";
import "./globals.css";
import { Roboto_Flex, Montserrat } from "next/font/google";

const roboto = Roboto_Flex({ subsets: ["latin"], variable: "--font-roboto" });
const montserrat = Montserrat({
  subsets: ["latin"],
  variable: "--font-montserrat",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} ${montserrat.variable} font-sans`}>
        <div className="grid min-h-screen w-screen h-screen grid-cols-[250px_auto]">
          <Menu />
          <main className="overflow-x-auto py-6">{children}</main>
        </div>
      </body>
    </html>
  );
}
