import Providers from '../services/providers'
import Menu from '@/components/Menu/Menu'
import './globals.css'
import { Montserrat } from 'next/font/google'
import { cookies } from 'next/headers'
import React from 'react'

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--font-montserrat',
})

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const isAuthenticated = cookies().has('token')

  return (
    <html lang="en">
      <body className={`${montserrat.variable} bg-gray-50 font-sans`}>
        <Providers>
          {isAuthenticated ? (
            <div className="grid h-screen min-h-screen w-screen grid-cols-[250px_auto]">
              <Menu />
              <main className="overflow-x-auto p-6">{children}</main>
            </div>
          ) : (
            children
          )}
        </Providers>
      </body>
    </html>
  )
}
